### ISSUE TITLE
From crvEURS vault, can't zap into other coins

### ISSUE THREAD

**Issue by RyanCwynar** [yearn/yearn-finance#333]
## Description

When attempting to withdraw yields from crvEURS vault, unable to zap into other currencies.

## Steps to reproduce

1. When withdrawing from crvEURS vault, select anything that isn't crvEURS
2. Enter an amount (sidenote: text says "crvEURS denominated in USDC", but when clicking Max the value is clearly still denominated in crvEURS)
3. Click withdraw *UI does nothing* (console output shown in screenshots)

**Expected behavior**
Expect metamask to open and start a transaction to withdraw yields to the selected currency

Also expect when selecting a currency from the dropdown that when I click max, the value will be translated into the max available in that currency.

**Screenshots**

![image](https://user-images.githubusercontent.com/5241542/119228299-5e273300-bae0-11eb-9c84-93533a43de4b.png)
![image](https://user-images.githubusercontent.com/5241542/119228369-b9592580-bae0-11eb-8ba1-56d9fa97e831.png)
UI issue where clicking Max only  references the native token of the vault, doesn't convert the value into something ETH/USDC/WBTC denominated as expected.
![image](https://user-images.githubusercontent.com/5241542/119228404-d988e480-bae0-11eb-8eab-5c46e474ebc8.png)

## Versions

- Browser: Brave and Chrome

**Comment by dudesahn** [comment]
@RyanCwynar could you try this again now? We worked with zapper and they updated their zapOut path for this so it should be fixed

**Comment by RyanCwynar** [comment]
Hmm. Still showing a similar thing

![image](https://user-images.githubusercontent.com/5241542/123557219-aed42080-d75d-11eb-9f19-10e44ab29002.png)

Worth noting that I've since migrated to the v2 vault.

I've also got funds in the crvALUSD and crvLUSD vaults. I think the same issue exists there.

I'm wondering about the relative complexity of making that zap... since the token being held is crvALUSD or crvEURS or crvLUSD, that's quite a lot of transformations that need to happen. Has to go from the vault token > the curve LP token > the underlying asset of the pool > swap the exotic stable for a more common stable (probably in curve) > then swap the common stable for whatever the zapper wants to give back... ETH/WETH/WBTC/USDC/DAI

I'm curious about what part of the pipeline is breaking down.

**Comment by dudesahn** [comment]
When you try to zap out of the v2 Curve EURS vault, you still get an error message? 

Zapper told us the issue with EURS was that 0x (who they route through) was using a super low-liquidity pool for zaps for some reason; which they updated. If it's still failing, I can reach back out to zapper to investigate further.

**Comment by RyanCwynar** [comment]
Actually it does look like it's firing now. Haven't executed a withdrawal, but error is gone and I'm seeing Metamask open up and preparing the contract interaction

**Comment by dudesahn** [comment]
Closing as this appears to have been resolved by zapper's fixes
